var EXPORTED_SYMBOLS = ["defaultPrefsList"];

var defaultPrefsList = [
  { name: 'cb_05m', id: 'moresnooze.cb_05m', label: '__MSG_moreSnooze.cb_05m__', value: 5, default: true },
  { name: 'cb_10m', id: 'moresnooze.cb_10m', label: '__MSG_moreSnooze.cb_10m__', value: 10, default: true },
  { name: 'cb_15m', id: 'moresnooze.cb_15m', label: '__MSG_moreSnooze.cb_15m__', value: 15, default: true },
  { name: 'cb_20m', id: 'moresnooze.cb_20m', label: '__MSG_moreSnooze.cb_20m__', value: 20, default: false },
  { name: 'cb_30m', id: 'moresnooze.cb_30m', label: '__MSG_moreSnooze.cb_30m__', value: 30, default: true },
  { name: 'cb_40m', id: 'moresnooze.cb_40m', label: '__MSG_moreSnooze.cb_40m__', value: 40, default: false },
  { name: 'cb_45m', id: 'moresnooze.cb_45m', label: '__MSG_moreSnooze.cb_45m__', value: 45, default: true },
  { name: 'cb_50m', id: 'moresnooze.cb_50m', label: '__MSG_moreSnooze.cb_50m__', value: 50, default: false },
  { name: 'cb_01h', id: 'moresnooze.cb_01h', label: '__MSG_moreSnooze.cb_01h__', value: 60, default: true },
  { name: 'cb_02h', id: 'moresnooze.cb_02h', label: '__MSG_moreSnooze.cb_02h__', value: 120, default: true },
  { name: 'cb_03h', id: 'moresnooze.cb_03h', label: '__MSG_moreSnooze.cb_03h__', value: 180, default: false },
  { name: 'cb_06h', id: 'moresnooze.cb_06h', label: '__MSG_moreSnooze.cb_06h__', value: 360, default: false },
  { name: 'cb_09h', id: 'moresnooze.cb_09h', label: '__MSG_moreSnooze.cb_09h__', value: 540, default: false },
  { name: 'cb_12h', id: 'moresnooze.cb_12h', label: '__MSG_moreSnooze.cb_12h__', value: 720, default: false },
  { name: 'cb_15h', id: 'moresnooze.cb_15h', label: '__MSG_moreSnooze.cb_15h__', value: 900, default: false },
  { name: 'cb_01d', id: 'moresnooze.cb_01d', label: '__MSG_moreSnooze.cb_01d__', value: 1440, default: true },
  { name: 'cb_02d', id: 'moresnooze.cb_02d', label: '__MSG_moreSnooze.cb_02d__', value: 2880, default: false },
  { name: 'cb_03d', id: 'moresnooze.cb_03d', label: '__MSG_moreSnooze.cb_03d__', value: 4320, default: false },
  { name: 'cb_04d', id: 'moresnooze.cb_04d', label: '__MSG_moreSnooze.cb_04d__', value: 5760, default: false },
  { name: 'cb_05d', id: 'moresnooze.cb_05d', label: '__MSG_moreSnooze.cb_05d__', value: 7200, default: false },
  { name: 'cb_01w', id: 'moresnooze.cb_01w', label: '__MSG_moreSnooze.cb_01w__', value: 10080, default: false },
  { name: 'cb_02w', id: 'moresnooze.cb_02w', label: '__MSG_moreSnooze.cb_02w__', value: 20160, default: false },
]