var fieldList = [
  { name: 'cb_05m', id: 'moreSnooze.cb_05m', value: 5, default: true },
  { name: 'cb_10m', id: 'moreSnooze.cb_10m', value: 10, default: true },
  { name: 'cb_15m', id: 'moreSnooze.cb_15m', value: 15, default: true },
  { name: 'cb_20m', id: 'moreSnooze.cb_20m', value: 20, default: false },
  { name: 'cb_30m', id: 'moreSnooze.cb_30m', value: 30, default: true },
  { name: 'cb_40m', id: 'moreSnooze.cb_40m', value: 40, default: false },
  { name: 'cb_45m', id: 'moreSnooze.cb_45m', value: 45, default: true },
  { name: 'cb_50m', id: 'moreSnooze.cb_50m', value: 50, default: false },
  { name: 'cb_01h', id: 'moreSnooze.cb_01h', value: 60, default: true },
  { name: 'cb_02h', id: 'moreSnooze.cb_02h', value: 120, default: true },
  { name: 'cb_03h', id: 'moreSnooze.cb_03h', value: 180, default: false },
  { name: 'cb_06h', id: 'moreSnooze.cb_06h', value: 360, default: false },
  { name: 'cb_09h', id: 'moreSnooze.cb_09h', value: 540, default: false },
  { name: 'cb_12h', id: 'moreSnooze.cb_12h', value: 720, default: false },
  { name: 'cb_15h', id: 'moreSnooze.cb_15h', value: 900, default: false },
  { name: 'cb_01d', id: 'moreSnooze.cb_01d', value: 1440, default: true },
  { name: 'cb_02d', id: 'moreSnooze.cb_02d', value: 2880, default: false },
  { name: 'cb_03d', id: 'moreSnooze.cb_03d', value: 4320, default: false },
  { name: 'cb_04d', id: 'moreSnooze.cb_04d', value: 5760, default: false },
  { name: 'cb_05d', id: 'moreSnooze.cb_05d', value: 7200, default: false },
  { name: 'cb_01w', id: 'moreSnooze.cb_01w', value: 10080, default: false },
  { name: 'cb_02w', id: 'moreSnooze.cb_02w', value: 20160, default: false },
]